## Criação do Dataset para a Questão 5

In [25]:
import numpy as np
import math

def createStepArray(arraySize, stepSize):
    """ 
    Creates a new array of numbers spaced by stepSize
    """
    arr = []
    
    for i in range(arraySize):
        arr.append(stepSize*i)
        
    return arr


def generateDataset_Q5(datasetSize, stepSize):
    """ 
    Generates dataset for training using Q5 function and the fact that each entry depends on the anterior one
    """
    
    X = createStepArray(datasetSize, stepSize)
    Y = []
    
    Y.append(0) # Initial value
    
    
    # Creates datasetSize examples
    for i in range(1, datasetSize):
        Y.append(np.sin(X[i-1] + (np.square(np.sin(X[i-1]))))) # Desired function, in which each entry depends on the anterior
        
    return X, Y

display(generateDataset_Q5(20, 0.1))

([0.0,
  0.1,
  0.2,
  0.30000000000000004,
  0.4,
  0.5,
  0.6000000000000001,
  0.7000000000000001,
  0.8,
  0.9,
  1.0,
  1.1,
  1.2000000000000002,
  1.3,
  1.4000000000000001,
  1.5,
  1.6,
  1.7000000000000002,
  1.8,
  1.9000000000000001],
 [0,
  0.0,
  0.10974521305070993,
  0.23718730112028194,
  0.377719585828099,
  0.5240903251985883,
  0.6667569920887635,
  0.7948868797643719,
  0.8979180191463156,
  0.9673607748354711,
  0.9983647958476117,
  0.9905922880363636,
  0.9481431714172184,
  0.8785871661282713,
  0.7914320654287149,
  0.6964808198891718,
  0.6024733589871253,
  0.5162317780834922,
  0.4423287159995988,
  0.3831585918377165])

In [ ]:
import numpy as np
import math


def createDataSetL1Q5(datasetSize, lookahead=1):
    """ 
    Generates dataset for training using Q5 function and the fact that each entry depends on the anterior one
    """
    
    X = np.linspace(0, 100, datasetSize+lookahead)
    
    Y = []
    
    for xi in X:
        Y.append(np.sin(xi + (np.square(np.sin(xi))))) 

    np.roll(Y)
    
    
    y =x 
    
    
    x =1 y =3
    x =2 y =4
    x =3 y =5
    
    # Creates datasetSize examples
    for i in range(1, datasetSize):
        Y.append(np.sin(X[i-1] + (np.square(np.sin(X[i-1]))))) # Desired function, in which each entry depends on the anterior
        
    return X, Y

display(generateDataset_Q5(20, 0.1))

In [10]:
import numpy as np


array([  0.        ,   0.1010101 ,   0.2020202 ,   0.3030303 ,
         0.4040404 ,   0.50505051,   0.60606061,   0.70707071,
         0.80808081,   0.90909091,   1.01010101,   1.11111111,
         1.21212121,   1.31313131,   1.41414141,   1.51515152,
         1.61616162,   1.71717172,   1.81818182,   1.91919192,
         2.02020202,   2.12121212,   2.22222222,   2.32323232,
         2.42424242,   2.52525253,   2.62626263,   2.72727273,
         2.82828283,   2.92929293,   3.03030303,   3.13131313,
         3.23232323,   3.33333333,   3.43434343,   3.53535354,
         3.63636364,   3.73737374,   3.83838384,   3.93939394,
         4.04040404,   4.14141414,   4.24242424,   4.34343434,
         4.44444444,   4.54545455,   4.64646465,   4.74747475,
         4.84848485,   4.94949495,   5.05050505,   5.15151515,
         5.25252525,   5.35353535,   5.45454545,   5.55555556,
         5.65656566,   5.75757576,   5.85858586,   5.95959596,
         6.06060606,   6.16161616,   6.26262626,   6.36

In [12]:
np.linspace(0, 20, 200)
    

array([  0.        ,   0.10050251,   0.20100503,   0.30150754,
         0.40201005,   0.50251256,   0.60301508,   0.70351759,
         0.8040201 ,   0.90452261,   1.00502513,   1.10552764,
         1.20603015,   1.30653266,   1.40703518,   1.50753769,
         1.6080402 ,   1.70854271,   1.80904523,   1.90954774,
         2.01005025,   2.11055276,   2.21105528,   2.31155779,
         2.4120603 ,   2.51256281,   2.61306533,   2.71356784,
         2.81407035,   2.91457286,   3.01507538,   3.11557789,
         3.2160804 ,   3.31658291,   3.41708543,   3.51758794,
         3.61809045,   3.71859296,   3.81909548,   3.91959799,
         4.0201005 ,   4.12060302,   4.22110553,   4.32160804,
         4.42211055,   4.52261307,   4.62311558,   4.72361809,
         4.8241206 ,   4.92462312,   5.02512563,   5.12562814,
         5.22613065,   5.32663317,   5.42713568,   5.52763819,
         5.6281407 ,   5.72864322,   5.82914573,   5.92964824,
         6.03015075,   6.13065327,   6.23115578,   6.33

In [13]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [19]:
list(np.zeros(10))

[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]